spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/hackaton_fiap
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sendgrid:
    api-key:
    from:
      email:

application:
  security:
    jwt:
      secret-key:
      expiration:
  mailing:
    frontend:
      activation-url: http://192.168.1.6:8089/api/v1/auth/activate-account?token=
      reset-password-url: http://192.168.1.6:4200/reset-password-url